/* PROGRAMA QUE IMPRIME LA TABLA DE MULTIPLICAR DE UN NÚMERO*/
SET SERVEROUTPUT ON;
DECLARE
T NUMBER;
N NUMBER;
BEGIN
T:=&TABLA;
DBMS_OUTPUT.PUT_LINE('TABLA: '||T);
FOR N IN 0..10 LOOP
	DBMS_OUTPUT.PUT_LINE(N||' X '||T||' = '||N*T);
END LOOP;

END;
/
