DECLARE
N1 NUMBER:=5;
N2 NUMBER:=3;
R1 NUMBER;
R2 NUMBER;
BEGIN
R1:=FACT(N1);
R2:=FACT(N2);
DBMS_OUTPUT.PUT_LINE('EL FACTORIAL DE '||N1||' ES '||R1);
DBMS_OUTPUT.PUT_LINE('EL FACTORIAL DE '||N2||' ES '||R2);

END;
/
