CREATE OR REPLACE PROCEDURE MUESTRA_CLIENTE(CO IN CLIENTES.CODIGOCLIENTE%TYPE)AS
NOMBRECLI CLIENTES.NOMBRECLIENTE%TYPE;
CIUDADCLI CLIENTES.CIUDAD%TYPE;
PAISCLI CLIENTES.PAIS%TYPE;
BEGIN
SELECT NOMBRECLIENTE,CIUDAD,PAIS INTO NOMBRECLI,CIUDADCLI,PAISCLI FROM CLIENTES WHERE CODIGOCLIENTE=CO;
DBMS_OUTPUT.PUT_LINE('CLIENTE Nº: '||CO);
DBMS_OUTPUT.PUT_LINE('NOMBRE    : '||NOMBRECLI);
DBMS_OUTPUT.PUT_LINE('CIUDAD    : '||CIUDADCLI);
DBMS_OUTPUT.PUT_LINE('PAIS      : '||PAISCLI);

END;
/
