/* PROGRAMA QUE ME IMPRIME LA POTENCIA DE UN NÚMERO*/
SET SERVEROUTPUT ON;
DECLARE
BASE NUMBER;
EXPONENTE NUMBER;
POT NUMBER:=1;
BEGIN
BASE:=&BASE;
EXPONENTE:=&EXPONENTE;
fOR I IN 1..EXPONENTE LOOP
	POT:=POT*BASE;
END LOOP;
	DBMS_OUTPUT.PUT_LINE(BASE||' ELEVADO A '||EXPONENTE||' ES '||POT);

END;
/
