CREATE OR REPLACE FUNCTION ES_PRIMO(N IN NUMBER) RETURN BOOLEAN
AS
PRIMO BOOLEAN:=TRUE;
I NUMBER:=2;
BEGIN
WHILE I<=(N/2) AND PRIMO LOOP
	IF MOD(N,I)=0 THEN
		PRIMO:=FALSE;
	END IF;
	I:=I+1;
END LOOP;
RETURN PRIMO;
END;
/
