/* PROGRAMA QUE SUMA LOS CIEN PRIMEROS NÚMEROS*/
SET SERVEROUTPUT ON;
DECLARE
SUMA NUMBER:=0;
N NUMBER;
BEGIN
FOR N IN 1..100 LOOP
	SUMA:=SUMA+N;
END LOOP;
DBMS_OUTPUT.PUT_LINE('LA SUMA ES :'||SUMA);
END;
/
