CREATE OR REPLACE PROCEDURE LISTAR_EMPLEADOS_2(CO IN EMPLEADOS.CODIGOOFICINA%TYPE)AS
CURSOR cursor_Empleados IS SELECT NOMBRE,APELLIDO1,APELLIDO2,CIUDAD FROM EMPLEADOS NATURAL JOIN OFICINAS WHERE CODIGOOFICINA=CO;

BEGIN
FOR regEmpleado IN cursor_Empleados LOOP
	DBMS_OUTPUT.PUT_LINE(regEmpleado.NOMBRE||' '||regEmpleado.Apellido1||' '||regEmpleado.APELLIDO2||' '||regEmpleado.CIUDAD);
END LOOP;
END;
/
