CREATE OR REPLACE FUNCTION DIVISION(DIVIDENDO IN NUMBER, DIVISOR IN NUMBER, RESTO OUT NUMBER) RETURN NUMBER AS
COCIENTE NUMBER:=0;
N NUMBER;
BEGIN
N:=DIVIDENDO;
WHILE N>=DIVISOR LOOP
	N:=N-DIVISOR;
	COCIENTE:=COCIENTE+1;
END LOOP;
RESTO:=N;
RETURN COCIENTE;
END;
/
