/* PROGRAMA QUE IMPRIME LOS DIVISORES DE UN NÚMERO*/
SET SERVEROUTPUT ON;
DECLARE
D NUMBER;
N NUMBER;
BEGIN
N:=&numero;
FOR D IN REVERSE 1..N LOOP
	IF MOD(N,D)=0 THEN
		DBMS_OUTPUT.PUT_LINE(D);
	END IF;
END LOOP;
END;
/
