/* PROGRAMA QUE IMPRIME EL VALOR DE UNA NOTA COMO TEXTO */
SET SERVEROUTPUT ON;
DECLARE
NOTA NUMBER;
B NUMBER;
C NUMBER;
BEGIN
NOTA:=&NOTA;
CASE NOTA
WHEN 0 THEN
	DBMS_OUTPUT.PUT_LINE('INSUFICIENTE');
WHEN 1 THEN
	DBMS_OUTPUT.PUT_LINE('INSUFICIENTE');
WHEN 2 THEN
	DBMS_OUTPUT.PUT_LINE('INSUFICIENTE');
WHEN 3 THEN
	DBMS_OUTPUT.PUT_LINE('INSUFICIENTE');
WHEN 4 THEN
	DBMS_OUTPUT.PUT_LINE('INSUFICIENTE');
WHEN 5 THEN
	DBMS_OUTPUT.PUT_LINE('SUFICIENTE');
WHEN 6 THEN
	DBMS_OUTPUT.PUT_LINE('BIEN');
WHEN 7 THEN
	DBMS_OUTPUT.PUT_LINE('NOTABLE');
WHEN 8 THEN
	DBMS_OUTPUT.PUT_LINE('NOTABLE');
WHEN 9 THEN
	DBMS_OUTPUT.PUT_LINE('SOBRESALIENTE');
WHEN 10 THEN
	DBMS_OUTPUT.PUT_LINE('MATÍCULA DE HONOR');
ELSE
	DBMS_OUTPUT.PUT_LINE('NOTA NO VÁLIDA');
END CASE;

END;
/
