/* PROGRAMA QUE ME DICE SI UN NÚMERO ES PRIMO O NO*/
SET SERVEROUTPUT ON;
DECLARE
PRIMO BOOLEAN:=TRUE;
N NUMBER;
I NUMBER:=2;
BEGIN
N:=&NUMERO;
WHILE PRIMO AND I<= N/2 LOOP
	IF MOD(N,I)=0 THEN
		PRIMO:=FALSE;
	END IF;
	I:=I+1;
END LOOP;
IF PRIMO THEN 
	DBMS_OUTPUT.PUT_LINE('El número '||N||' es primo');
ELSE
	
	DBMS_OUTPUT.PUT_LINE('EL número '||N||' NO es primo');
END IF;

END;
/
