/* PROGRAMA QUE IMPRIME LA TABLA DE MULTIPLICAR DE LOS 10 PRIMEROS NÚMEROS*/
SET SERVEROUTPUT ON;
DECLARE
T NUMBER;
N NUMBER;
BEGIN

FOR T IN 1..10 LOOP
	DBMS_OUTPUT.PUT_LINE('TABLA DEL '||T);
	FOR N IN 0..10 LOOP
		DBMS_OUTPUT.PUT_LINE(N||' X '||T||' = '||N*T);
	END LOOP;
		DBMS_OUTPUT.PUT_LINE('------------------------');
END LOOP;

END;
/
