DECLARE
N1 NUMBER:=100;
N2 NUMBER:=300;
BEGIN
	DBMS_OUTPUT.PUT_LINE('VALOR DE N1: '||N1||', VALOR DE N2: '||N2);
	INTERCAMBIA(N1,N2);
	DBMS_OUTPUT.PUT_LINE('VALOR DE N1: '||N1||', VALOR DE N2: '||N2);
	INTERCAMBIA(N1,N2);
	DBMS_OUTPUT.PUT_LINE('VALOR DE N1: '||N1||', VALOR DE N2: '||N2);


END;
/
