/* PROGRAMA QUE EN ORDEN CRECIENTE DOS NÚMEROS LEÍDOS POR TECLADO */
SET SERVEROUTPUT ON;
DECLARE
A NUMBER;
B NUMBER;
C NUMBER;
BEGIN
A:=&A;
B:=&B;
C:=&C;
IF A<B THEN
	IF A<C THEN
		IF B<C THEN
			DBMS_OUTPUT.PUT_LINE(A||', '||B||', '||C);
		ELSE
			DBMS_OUTPUT.PUT_LINE(A||', '||C||', '||B);
		END IF;
	ELSE
		DBMS_OUTPUT.PUT_LINE(C||', '||A||', '||B);
	END IF;
ELSE
	IF B<C THEN
		IF A<C THEN
			DBMS_OUTPUT.PUT_LINE(B||', '||A||', '||C);
		ELSE
			DBMS_OUTPUT.PUT_LINE(B||', '||C||', '||A);
		END IF;
	ELSE
		DBMS_OUTPUT.PUT_LINE(C||', '||B||', '||A);
	END IF;
END IF;
END;
/
