/* PROGRAMA QUE ME IMPRIME EL FACTORIAL DE UN NÚMERO
EL FACTORIAL ES ESE NÚMERO MULTIPLICADO POR TODOS LOS MENORES DE ÉL
EJMPLO FACTORIAL DE 5= 5x4x3x2x1*/
SET SERVEROUTPUT ON;
DECLARE
N NUMBER;
FACT NUMBER:=1;
BEGIN
N:=&NUMERO;
fOR I IN 1..N LOOP
	FACT:=FACT*I;
END LOOP;
	DBMS_OUTPUT.PUT_LINE('EL FACTORIAL DE '||N||' ES '||FACT);

END;
/
