CREATE OR REPLACE PROCEDURE LISTAR_PRIMOS(N IN NUMBER) 
AS
TOTAL_PRIMOS NUMBER:=0; 
POSIBLE_PRIMO NUMBER:=1; 
BEGIN

WHILE TOTAL_PRIMOS<N LOOP
	IF ES_PRIMO(POSIBLE_PRIMO) THEN
		DBMS_OUTPUT.PUT_LINE(POSIBLE_PRIMO);
		TOTAL_PRIMOS:=TOTAL_PRIMOS+1;
	END IF;
	POSIBLE_PRIMO:=POSIBLE_PRIMO+1;
END LOOP;
END;
/
