/* PROGRAMA QUE ME DICE SI UN NÚMERO ES PRIMO O NO*/
SET SERVEROUTPUT ON;
DECLARE
PRIMO BOOLEAN:=TRUE;
N NUMBER;
I NUMBER;
BEGIN
FOR N IN 1..99 LOOP
	PRIMO:=TRUE;
	I:=2;
	WHILE PRIMO AND I<= N/2 LOOP
		IF MOD(N,I)=0 THEN
			PRIMO:=FALSE;
		END IF;
		I:=I+1;
	END LOOP;
	IF PRIMO THEN 
		DBMS_OUTPUT.PUT_LINE(N);
	END IF;
END LOOP;
END;
/
